### ISSUE TITLE
DEPENDS in catkin_package() not adding package INCLUDE_DIRS 

### ISSUE THREAD

**Issue by ojasjoshi** [ROBOTIS-GIT/turtlebot3_simulations#111]
Refer to the following fix: https://github.com/ros/catkin/issues/552

**Comment by ashekim** [comment]
@ojasjoshi 

I'm sorry for the late reply.
We will discuss it in the team and update our package. Thank you so much for your contribution.

Regards,
Ashe

**Comment by ROBOTIS-Will** [comment]
@ojasjoshi 
Thank you for your contribution!
