### ISSUE TITLE
turtlebot3 drive not working

### ISSUE THREAD

**Issue by jas705** [ROBOTIS-GIT/turtlebot3_simulations#117]
Hi, I am trying to run a turtlebot3 drive for collision avoidance.
$ export TURTLEBOT3_MODEL=burger
$ roslaunch turtlebot3_gazebo turtlebot3_world.launch
$ export TURTLEBOT3_MODEL=burger
$ roslaunch turtlebot3_gazebo turtlebot3_simulation.launch

when running simulation. launch file the robot should move automatically in the world. In this case, the turtlebot3 drive node is initializing and the Simulation node init msg can be seen, but the turtlebot3 is not moving in the gazebo. It is standing still.

**Comment by ashekim** [comment]
Hi @jas705 
I'm sorry for the late reply.

Please check [▶] button in Gazebo to start simulation.
If it's playing[▶], please try reinstall package.
Thank you.

**Comment by ashekim** [comment]
This issue has been closed as there weren't recent activities. 
Please feel free to reopen this thread if there's any opinion to throw. Thanks.
