### ISSUE TITLE
Where should I clone this

### ISSUE THREAD

**Issue by HatcherRobotics** [ROBOTIS-GIT/turtlebot3_simulations#122]
Do I need to git clone all of this  in the folder"src"under"catkin_ws"

**Comment by ashekim** [comment]
@HatcherRobotics 

Hi. Thank you for your questions.

Please refer to the link below.
[11. [ROS 1] Simulation](https://emanual.robotis.com/docs/en/platform/turtlebot3/simulation/#ros-1-simulation) 

Thank you.

**Comment by HatcherRobotics** [comment]
@ashekim Thanks bro,I got it!

**Comment by ashekim** [comment]
@HatcherRobotics 
I would greatly appreciate it.
If you have any question or suggest, please ask to me any time. 
Thanks :)
