### ISSUE TITLE
env-hooks in ros2 branches

### ISSUE THREAD

**Issue by joe28965** [ROBOTIS-GIT/turtlebot3_simulations#123]
I was curious why no [env hooks](https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-Migration:-Gazebo-ROS-Paths#env-hooks) are used in any of the ros2 branches. This will eliminate the need for people to manually add the GAZEBO_MODEL_PATH to their bashrc

`echo 'export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:~/turtlebot3_ws/src/turtlebot3/turtlebot3_simulations/turtlebot3_gazebo/models' >> ~/.bashrc`

Is there a specific reason as to why it's preferred to do this manually?

**Comment by ashekim** [comment]
@joe28965 

Hi. @joe28965 
We will discuss it in the team and update our package. 
Thank you so much for your contribution.

**Comment by Rayman** [comment]
@joe28965 I've created a PR with a much cleaner way here: https://github.com/ROBOTIS-GIT/turtlebot3_simulations/pull/129. I hope you can take a look if it solves your problem.

**Comment by ROBOTIS-Will** [comment]
This fix had been merged and released in the recent ROS2 update.
https://github.com/ros/rosdistro/pull/28006
Thank you @Rayman , @joe28965 for your contributions!
