### ISSUE TITLE
Possibly wrong collision box for `camera_rgb_optical_frame`

### ISSUE THREAD

**Issue by goekce** [ROBOTIS-GIT/turtlebot3_simulations#136]
I simulated Waffle-pi in Gazebo and noticed that there is a collision box defined in front of Waffle-pi:

https://github.com/ROBOTIS-GIT/turtlebot3_simulations/blob/ff1d521a20c67b516b40361463285872ba14f3dd/turtlebot3_gazebo/models/turtlebot3_waffle_pi/model.sdf#L368-L375

Due to this collision box Waffle-pi crashes early to walls. Is this collision box maybe a forgotten artifact from Intelsense camera or is it a feature?
 
![a](https://user-images.githubusercontent.com/18174744/102819140-3ae24580-43d3-11eb-8e39-f4deee63247c.png)

**Comment by ROBOTIS-Will** [comment]
@goekce 
Thank you for reporting the issue :+1: 
I'll remove this collision box in the next patch.

**Comment by ROBOTIS-Will** [comment]
Closing this issue as the fix has been applied in the recent release.
Thank you.
