### ISSUE TITLE
Release into Foxy

### ISSUE THREAD

**Issue by SteveMacenski** [ROBOTIS-GIT/turtlebot3_simulations#143]

**Comment by SteveMacenski** [comment]
https://build.ros2.org/job/Fbin_uF64__turtlebot3_gazebo__ubuntu_focal_amd64__binary/ builds are also failing

**Comment by ROBOTIS-Will** [comment]
Hi @SteveMacenski 
Thank you for the kind ping.
I'll look into it and rectify the simulation package.
This will be included in the February release next week.

**Comment by SteveMacenski** [comment]
Thanks! We've had a bunch of users run into this as they try to use the getting started / build instructions for TB3 and Nav2.

**Comment by ROBOTIS-Will** [comment]
Updates had been merged and successfully built as a binary package for Foxy.
https://github.com/ros/rosdistro/pull/28404
Thanks!

**Comment by SteveMacenski** [comment]
Awesome thanks!
