### ISSUE TITLE
Simulations in python

### ISSUE THREAD

**Issue by PandaJules** [ROBOTIS-GIT/turtlebot3_simulations#18]
I looked through several ROBOTIS repos and most seem to be in C++. I am currently working on a project, involving ROS, Gazebo and Turtlebot3, where my code is all in Python. I was wondering whether there have been any plans to have the code from this repo translated to Python? Right now I am writing my own gazebo_ros_turtlebot3 and turtlebot3_fake, translating your .cpp files to .py files. I think for beginners who want to pick up robotics, Python would definitely be a more friendly environment to work in.

**Comment by routiful** [comment]
Hi, @PandaJules  :)

Yes, I couldn't agree with you more. So our team is ready to Python code. It will be released next year.
Thank you for your opinion.

Thanks
Darby
