### ISSUE TITLE
Export gazebo_model path instead of requiring users to install the models

### ISSUE THREAD

**Issue by tfoote** [ROBOTIS-GIT/turtlebot3_simulations#6]
In the docs right now http://turtlebot3.robotis.com/en/latest/simulation.html the user is explicitly instructed to install the models. This can easily lead to outdated models lingering around.

Instead the GAZEBO_MODEL_PATH it should be declared in the package.xml like this: https://github.com/osrf/car_demo/blob/master/car_demo/package.xml#L25

Also while looking at this the models should not be in the `worlds` subdirectory either but in a `models` subdirectory for clarity.

**Comment by routiful** [comment]
Hi :)

I apply GAZEBO_MODEL_PATH and change name of subdirectory.
I appreciate your contribution.

Thank you!
