### ISSUE TITLE
Realsense frame incorrect

### ISSUE THREAD

**Issue by allenh1** [ROBOTIS-GIT/turtlebot3_simulations#7]
Everything works pretty well, but the depth camera seems to be in the wrong frame.

Here's the view in RVIZ:

![turtlebot3_gazebo](https://user-images.githubusercontent.com/2013091/28189888-fed14da0-67dc-11e7-9aff-de44a048b61c.png)

Here's the view in Gazebo (7.8):

![screenshot from 2017-07-13 15-03-41](https://user-images.githubusercontent.com/2013091/28189959-6d8f837e-67dd-11e7-9e4f-6af7554d9d18.png)

**Comment by routiful** [comment]
Hi :)

I tried to change frame using tf but it does not works.
It needs additional publisher to change orientation of frame.
I attached some [reference link](http://answers.gazebosim.org/question/4266/gazebo-15-libgazebo_openni_kinectso-pointcloud-data-is-rotated-and-flipped/)

If you have any idea to change frame, please notice us.
Thanks.

**Comment by allenh1** [comment]
@routiful I think I'll go ahead add a static transform publisher to the fake turtlebot node. That should resolve this.

**Comment by routiful** [comment]
Hi @allenh1 

I add static transform publisher in turtlebot3_world.launch file.
You can check it in master branch.
![gazebo_depth_camera](https://user-images.githubusercontent.com/7092473/28858742-b2d8a284-778d-11e7-9220-bed393f04c30.png)


Thanks.

**Comment by allenh1** [comment]
Excellent! Nice work.

**Comment by cs408-ta** [comment]
I see that static transform publisher is now removed from turtlebot3_world.launch file. Can you please explain why is it not required anymore?

Thanks!

**Comment by sayali-purdue** [comment]
I see that static transform publisher is now removed from turtlebot3_world.launch file. Can you please explain why is it not required anymore?

Thanks!
