### ISSUE TITLE
Realsense collision box location in model.sdf for turtlebot3_waffle is not on the sensor

### ISSUE THREAD

**Issue by mhpanah** [ROBOTIS-GIT/turtlebot3_simulations#76]
In ROS2 branch, the pose values `<pose>0.069 -0.047 0.107 0 0 0</pose>` for realsense camera collision box in `turtlebot3_waffle/model.sdf` seems to be wrong.  With these values, in Gazebo the collision box is shown with offset from the actual location.  Please look at the attached image. 

![turtlebot3](https://user-images.githubusercontent.com/39755151/57103843-af86de80-6cdb-11e9-99ee-6e7b621b18aa.png)

**Comment by routiful** [comment]
I have amended. Please check again.

**Comment by routiful** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
