### ISSUE TITLE
ROS2: How to launch multiple TB3 robots in single world in gazebo

### ISSUE THREAD

**Issue by kishornaik10** [ROBOTIS-GIT/turtlebot3_simulations#83]
Hi,

I want to launch multiple TB3 robots in single world in gazebo simulator in ros2 environment.
How this can be done? please help

**Comment by routiful** [comment]
@kishornaik10 
You can refer to below launch file
https://github.com/ROBOTIS-GIT/turtlebot3_simulations/blob/master/turtlebot3_gazebo/launch/multi_turtlebot3.launch

**Comment by kishornaik10** [comment]
@routiful 

Thank you,
This launch file can be launch in ROS (i.e. melodic) but mine case is ROS2 (i.e. dashing).
[Github repo]
https://github.com/ROBOTIS-GIT/turtlebot3/tree/ros2 
https://github.com/ROBOTIS-GIT/turtlebot3_simulations/tree/ros2 

Can you suggest modification needed in launch files in ros2? or any sample example.
Thanks 
Kishor

**Comment by routiful** [comment]
@kishornaik10 
I didn't try to make launch file loading multiple TB3 in ROS2 yet.
But it seems to be not difficult to port it. 
Please feel free to comments while you have any problem when you port it :)

**Comment by routiful** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
