### ISSUE TITLE
High poly count in 3D models for non visible surfaces 

### ISSUE THREAD

**Issue by ruffsl** [ROBOTIS-GIT/turtlebot3_simulations#89]
While it's nice the the turtlebot 3 mode for gazebo remains accurate and has already been downsampled in polycount, the number of non-visible services seems a bit excessive. A small optimization may be to omit or hollow out services internal to mechanics and electronics that are non-visible to reduces the memory footprint for simulations.

![image](https://user-images.githubusercontent.com/2293573/64370262-f6127f80-cfd2-11e9-9538-155300000c02.png)

**Comment by ROBOTIS-Will** [comment]
Closing this issue as low poly model had been applied
https://github.com/ROBOTIS-GIT/turtlebot3_simulations/commit/7617863780e85e017c6fe916ac43620b4fa587d6
