### ISSUE TITLE
Turtlebot3 LIDAR Gazebo

### ISSUE THREAD

**Issue by FrancescoTerrosi** [ROBOTIS-GIT/turtlebot3_simulations#96]
Hello there,

I'm using Turtlebot3-Burger on Gazebo, with ROS-melodic on Ubuntu 18.04.
I need to use laser data to estimate the distance to an obstacle and the same data are used in order to detect any collision. The problem is that there is a "blank" area near the robot, before the actual LIDAR that in some occasions prevents the robot from detecting the actual collision. Here are a couple of screenshot that I hope will clarify the situaton.

My question is: is there any parameter I can modify in order to make this stuff work? Thanks
![As you can see that detected distance is 0.9 but the robot is sticking to the leg of the table](https://user-images.githubusercontent.com/33395865/67793563-f9763480-fa72-11e9-8045-db4d03a43832.png)

![That semi-transparent gray are is the leg of the table, clearly inside the laser circle](https://user-images.githubusercontent.com/33395865/67793630-1ad72080-fa73-11e9-9400-b61f4ccc7756.png)

**Comment by ROBOTIS-Will** [comment]
@FrancescoTerrosi 
Hi,
If you look at the TurtleBot3 gazebo model file below, there's a parameter that you can set the minimum and maximum range of Lidar(hls_lfcd_lds).
https://github.com/ROBOTIS-GIT/turtlebot3_simulations/blob/627856619241833f0394861771f79a5008d69ea3/turtlebot3_gazebo/models/turtlebot3_burger/model.sdf#L108
